<?php
/**
 * Braintree - Payment Gateway integration (Hosted Fields) with custom stylesheet and validation
 * ==============================================================================
 * 
 * @version v1.0: braintree_hosted_fields_with_style_demo.php 2016/05/13
 * @copyright Copyright (c) 2016, http://www.ilovephp.net
 * @author Sagar Deshmukh <sagarsdeshmukh91@gmail.com>
 * You are free to use, distribute, and modify this software
 * ==============================================================================
 *
 */

// Braintree library
require 'braintree/lib/Braintree.php';

$params = array(
	"testmode"   => "on",
	"merchantid" => "xxxxxxx",
	"publickey"  => "xxxxxxx",
	"privatekey" => "xxxxxxxxxxxxxxxxxxxxx",
);

if ($params['testmode'] == "on")
{
	Braintree_Configuration::environment('sandbox');
}
else
{
	Braintree_Configuration::environment('production');
}

Braintree_Configuration::merchantId($params["merchantid"]);
Braintree_Configuration::publicKey($params["publickey"]);
Braintree_Configuration::privateKey($params["privatekey"]);

if(isset($_POST['payment_method_nonce']))
{
	$sale = array(
				'amount'   => $_POST['amount'],
				'paymentMethodNonce' => $_POST['payment_method_nonce'],   // Autogenerated field from braintree
				'options' => array(
								'submitForSettlement'   => true,
								'storeInVaultOnSuccess' => true
							 )
			);
						
	$result = Braintree_Transaction::sale($sale);
	if ($result->success)
	{
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Braintree Hosted Fields Demo</title>
<link href="style.css" type="text/css" rel="stylesheet" />
<link href="hosted_field_style.css" type="text/css" rel="stylesheet" />
<style type="text/css">
td { text-align: center;}
</style>
</head>
<body>
<div align="center">
  <header>
    <h1 class="bt_title">Braintree Hosted Fields API Response</h1>
  </header>
  <h3>Braintree Customer Id</h3>
  <table cellpadding="0" cellspacing="0" border="1px solid #6c7151" width="50%">
    <tbody>
      <tr align="center">
        <td width="50%">id</td>
        <td width="50%"><?php echo($result->transaction->_attributes['customer']['id'])?></td>
      </tr>
    </tbody>
  </table>
  <h3>Transaction</h3>
  <table cellpadding="0" cellspacing="0" border="1px solid #6c7151" width="50%">
    <tbody>
      <tr align="center">
        <td width="50%">id</td>
        <td width="50%"><?php echo($result->transaction->id)?></td>
      </tr>
      <tr>
        <td>type</td>
        <td><?php echo($result->transaction->type)?></td>
      </tr>
      <tr>
        <td>amount</td>
        <td><?php echo($result->transaction->amount)?></td>
      </tr>
      <tr>
        <td>status</td>
        <td><?php echo($result->transaction->status)?></td>
      </tr>
      <tr>
        <td>created_at</td>
        <td><?php echo($result->transaction->createdAt->format('Y-m-d H:i:s'))?></td>
      </tr>
      <tr>
        <td>updated_at</td>
        <td><?php echo($result->transaction->updatedAt->format('Y-m-d H:i:s'))?></td>
      </tr>
    </tbody>
  </table>
  <h3>Payment</h3>
  <table cellpadding="0" cellspacing="0" border="1px solid #6c7151" width="50%">
    <tbody>
      <tr>
        <td width="50%">token</td>
        <td width="50%"><?php echo($result->transaction->creditCardDetails->token)?></td>
      </tr>
      <tr>
        <td>bin</td>
        <td><?php echo($result->transaction->creditCardDetails->bin)?></td>
      </tr>
      <tr>
        <td>last_4</td>
        <td><?php echo($result->transaction->creditCardDetails->last4)?></td>
      </tr>
      <tr>
        <td>card_type</td>
        <td><?php echo($result->transaction->creditCardDetails->cardType)?></td>
      </tr>
      <tr>
        <td>expiration_date</td>
        <td><?php echo($result->transaction->creditCardDetails->expirationDate)?></td>
      </tr>
      <tr>
        <td>cardholder_name</td>
        <td><?php echo($result->transaction->creditCardDetails->cardholderName)?></td>
      </tr>
      <tr>
        <td>customer_location</td>
        <td><?php echo($result->transaction->creditCardDetails->customerLocation)?></td>
      </tr>
    </tbody>
  </table>
</div>
</body>
</html>
<?php
	}
	else
	{
		echo "Error : ".$result->_attributes['message'];
	}
	//print_r($result);
	exit;
}
else
if (isset($_POST['action']) && $_POST['action'] == 'generateclienttoken')
{
	// Generate the nonce
	$clientToken = Braintree_ClientToken::generate();
	echo $clientToken; exit;
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Braintree Hosted Fields Demo</title>
<link href="style.css" type="text/css" rel="stylesheet" />
<link href="hosted_field_style.css" type="text/css" rel="stylesheet" />
</head>

<body>
<h1 class="bt_title">Braintree Hosted Fields with Custom Stylesheet</h1>
<form id="bt_custom_form" name="bt_custom_form" method="post" action="">
  <div class="loader_container">
    <div class="loader_img loader"></div>
  </div>
  <div class="bt_form_wrap hide invisible">
    <fieldset>
      <label for="bt_card_number">Card Number</label>
      <div id="bt_card_number" class="inputFields"></div>
      <span class="payment-method-icon"></span>
    </fieldset>
    <div style="height: 84px;">
      <fieldset>
        <div style="float:left; width:49%">
          <label for="bt_exp_date">Expiration (MM/YY)</label>
          <div id="bt_exp_date" class="inputFields"></div>
        </div>
        <div style="float:right; width:49%">
          <label for="bt_cvv">CVV Number</label>
          <div id="bt_cvv" class="inputFields"></div>
          <span id="cvv-icon" class="payment-method-icon"></span> </div>
      </fieldset>
    </div>
    <div>
      <fieldset>
        <div style="float:left; width:49%; margin-top:9px">
          <input type="checkbox" value="1" name="braintree_subscribe" style="visibility:visible; position:relative;">
          <label for="braintree_subscribe">Set as default payment method</label>
        </div>
        <div style="float:right; width:49%" class="btn_container">
          <input type="submit" name="" class="button-me green-btn button-small pay-btn" value="Add Card" style="width:100%; margin-top:0px;" />
          <input type="hidden" name="amount" value="10"  />
          <span class="loader_img"></span>
        </div>
      </fieldset>
    </div>
  </div>
  <br />
  <br />
  <center>
    <div id="bt_paypal_container"></div>
  </center>
</form>
<script type="text/javascript" src="https://js.braintreegateway.com/js/beta/braintree-hosted-fields-beta.18.min.js"></script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> 
<script src="hosted_field_style.js"></script>
</body>
</html>